show_header:
  default: true
  type: bool
  description:
    en: 'Toggle the title header in the widget'

hidden_groups:
  type: list
  list_type: group
  default: 10|11|12|13|14|3|0
  description:
    en: 'Select which groups should be hidden from the widget'

show_group_icons:
  type: bool
  default: true
  description:
    en: 'Toggle to show or hide the group icons. (Note: when toggled and no icons are set for the group, a default icon will be used)'

show_group_owner_icon:
  type: bool
  default: true
  description:
    en: 'Toggle to show or hide the group owner icon'

style:
  type: enum
  default: 'normal'
  choices:
    - 'normal'
    - 'boxed'
    - 'modern'
    - 'masonry'
  description:
    en: 'Select a theme style for the widget (use normal if you would like to override with your own custom CSS)'
